---
# Simple Playbook
- hosts: ocean
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  #become: yes
  #become_method: sudo  
  tasks:
  - name: ensure git is at the latest version
    apt:
      name: git
      state: latest
